[package]
name = "cosmic-settings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cascade = "1.0.0"
gtk4 = { version = "0.3.1", features = ["v4_4"] }
once_cell = "1.9.0"
