[package]
name = "cosmic-settings"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
cascade = "1.0.0"
fuzzy-matcher = "0.3.7"
gtk4 = { version = "0.3.1", features = ["v4_4"] }
once_cell = "1.9.0"

[build-dependencies]
grass = "0.10.8"
